# Generated by Django 4.2.11 on 2024-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mails',
            },
        ),
    ]
