# Generated by Django 4.2.11 on 2024-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_script', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mails',
            old_name='message',
            new_name='message_body',
        ),
        migrations.AddField(
            model_name='mails',
            name='mail_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='mail_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mails',
            name='mail_tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mails',
            name='read_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='sender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mails',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
