# Generated by Django 4.2.11 on 2024-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_script', '0003_remove_mails_created_by_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='mail_tag',
            field=models.CharField(default='INBOX', max_length=100),
        ),
        migrations.AddIndex(
            model_name='mails',
            index=models.Index(fields=['thread_id'], name='Mails_thread__c82b8a_idx'),
        ),
    ]
